spring:
  application:
    name: testtask
  datasource:
    url: jdbc:postgresql://localhost:6000/testtask_db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
springdoc:
  api-docs:
    path: /v3/api-docs
    url: classpath:static/swagger.yml
  swagger-ui:
    url: swagger.yaml
token:
  signing:
    key: JEOBJAOIDH1253BNMAPORAPLAMKQMNIBC907817HUA87H430JDC
security:
  basic:
    enabled: false